SELECT
    DRI.DRI_CODE AS "Référence SIB",
    DRI.SAC_CODE AS "Numéro de compte client",
    SCO.SCO_CODE AS "Code Isin",
    DRI.DRI_QUANTITY AS "Quantitet"
FROM
    DRI_HISTO DRI
INNER JOIN
    SECURITY_CODIF SCO
ON
    DRI.SEC_CODE = SCO.SEC_CODE
WHERE
    DRI.dri_create_date BETWEEN TO_DATE('01/01/2023', 'DD/MM/YYYY') AND TO_DATE('01/06/2023', 'DD/MM/YYYY')
    AND SCO.COF_CODE = 'ISIN';
